export const JOIN_ROOM_STARTED = 'JOIN_ROOM_STARTED'
export const JOIN_ROOM_SUCCESS = 'JOIN_ROOM_SUCCESS'
export const JOIN_ROOM_FAILURE = 'JOIN_ROOM_FAILURE'

export const GET_USER_STARTED = 'GET_USER_STARTED'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

export const SEND_MESSAGE_STARTED = 'SEND_MESSAGE_STARTED'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE'

export const GET_MESSAGE_STARTED = 'GET_MESSAGE_STARTED'
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS'
export const GET_MESSAGE_FAILURE = 'GET_MESSAGE_FAILURE'

export const CREATE_ROOM_STARTED = 'CREATE_ROOM_STARTED'
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS'
export const CREATE_ROOM_FAILURE = 'CREATE_ROOM_FAILURE'

export const REGISTER_USER_STARTED = 'REGISTER_USER_STARTED'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'

export const LOGIN_USER_STARTED = 'LOGIN_USER_STARTED'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

export const APPBAR_PAGE_NAME = 'APPBAR_PAGE_NAME'